- hosts: 127.0.0.1
  connection: local
  tasks:
  - file: path=~/.ssh mode=0700 state=directory
  - lineinfile: dest=~/.ssh/known_hosts create=yes state=present line="{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}" regexp='^github.com'
  - homebrew: name={{item}} state=present
    with_items:
    - ansible
    - caskroom/cask/brew-cask
    - tmux
  - homebrew_cask: name={{item}} state=present
    with_items:
    - eclipse-java
    - firefox
    - google-chrome
    - intellij-idea
    - iterm2
    - virtualbox
