- hosts: 127.0.0.1
  connection: local
  pre_tasks:
  - file: path=~/.ssh mode=0700 state=directory
  - lineinfile: dest=~/.ssh/known_hosts create=yes state=present line="{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}" regexp='^github.com'
  roles:
  - { role: dotfiles, tags: ['dotfiles'] }
  tasks:
  - command: creates=~/.ssh/id_rsa ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ''
  - homebrew: name={{item}} state=present
    tags:
    - brew
    with_items:
    - ansible
    - atool
    - boot2docker
    - coreutils
    - docker
    - git-annex
    - gnu-sed
    - gnupg
    - imagemagick
    - leiningen
    - myrepos
    - node
    - postgresql
    - pwgen
    - pwsafe
    - ssh-copy-id
    - stow
    - tcptraceroute
    - tig
    - tmux
    - xml2
  - homebrew_cask: name={{item}} state=present
    tags:
    - cask
    with_items:
    - bettertouchtool
    - eclipse-java
    - firefox
    - google-chrome
    - intellij-idea
    - iterm2
    - java
    - libreoffice
    - sublime-text
    - vagrant
    - virtualbox
  - homebrew: name={{item}} state=present
    tags:
    - brew
    with_items:
    - maven # requires java
  - gem: name={{item}}
    tags:
    - gem
    with_items:
    - compass
    - timetrap
  - npm: name={{item}} global=yes
    tags:
    - npm
    with_items:
    - bower
    - grunt-cli
  # convert to osx_defaults after ansible 2.0 is released
  - command: defaults write com.apple.finder _FXShowPosixPathInTitle -bool YES
  - command: defaults write com.apple.screensaver askForPasswordDelay -int 0
