- hosts: 127.0.0.1
  connection: local
  tasks:
  - homebrew: name={{item}} state=present
    with_items:
    - ansible
    - caskroom/cask/brew-cask
    - tmux
  - homebrew_cask: name={{item}} state=present
    with_items:
    - eclipse-java
    - firefox
    - google-chrome
    - intellij-idea
    - iterm2
    - virtualbox
