- hosts: 127.0.0.1
  connection: local
  pre_tasks:
  - file: path=~/.ssh mode=0700 state=directory
  - lineinfile: dest=~/.ssh/known_hosts create=yes state=present line="{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}" regexp='^github.com'
  roles:
  - { role: dotfiles, tags: ['dotfiles'] }
  tasks:
  - command: creates=~/.ssh/id_rsa ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ''
  - homebrew: name={{item}} state=present
    with_items:
    - ansible
    - caskroom/cask/brew-cask
    - tig
    - tmux
  - homebrew_cask: name={{item}} state=present
    with_items:
    - eclipse-java
    - firefox
    - google-chrome
    - intellij-idea
    - iterm2
    - vagrant
    - virtualbox
