- hosts: 127.0.0.1
  connection: local
  pre_tasks:
  - file: path=~/.ssh mode=0700 state=directory
  - lineinfile: dest=~/.ssh/known_hosts create=yes state=present line="{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}" regexp='^github.com'
  roles:
  - { role: dotfiles, tags: ['dotfiles'] }
  tasks:
  - command: creates=~/.ssh/id_rsa ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ''
  - homebrew: name={{item}} state=present
    tags:
    - brew
    with_items:
    - ansible
    - atool
    - caskroom/cask/brew-cask
    - git-annex
    - leiningen
    - maven
    - myrepos
    - node
    - postgresql
    - pwgen
    - pwsafe
    - tcptraceroute
    - tig
    - tmux
    - xml2
  - homebrew_cask: name={{item}} state=present
    tags:
    - cask
    with_items:
    - eclipse-java
    - firefox
    - google-chrome
    - intellij-idea
    - iterm2
    - java
    - vagrant
    - virtualbox
  - gem: name={{item}}
    tags:
    - gem
    with_items:
    - compass
    - timetrap
  - npm: name={{item}} global=yes
    tags:
    - npm
    with_items:
    - bower
    - grunt-cli
  # convert to osx_defaults after ansible 2.0 is released
  - command: defaults write com.apple.finder _FXShowPosixPathInTitle -bool YES
  - command: defaults write com.apple.screensaver askForPasswordDelay -int 0
